// Generated by CoffeeScript 1.10.0
var HideTheElementAfterAnimation, all_scripts, btn_click, head_panel_click_open, head_panel_close, left_menu_update, load_parts, main_menu_update, rat, rating, slider_toggle, social_hover;

rat = 0;

head_panel_click_open = function() {
  if ($('.head-user-panel').hasClass('display-block')) {
    return head_panel_close();
  } else {
    $('.head-user-panel').addClass('display-block');
    return $('.head-user-panel').css("display", "block").css("opacity", "1").unbind("transitionend webkitTransitionEnd oTransitionEnd otransitionend");
  }
};

head_panel_close = function() {
  $('.head-user-panel').css("opacity", "0").on('transitionend webkitTransitionEnd oTransitionEnd otransitionend', HideTheElementAfterAnimation);
  return $('.head-user-panel').removeClass('display-block');
};

HideTheElementAfterAnimation = function() {
  return $(".head-user-panel").css("display", "none");
};

main_menu_update = function() {
  var hdr, mn, slider;
  mn = $('#menu');
  hdr = $('.body').height();
  slider = $('.header-slider').height();
  if ($(this).scrollTop() > hdr) {
    mn.addClass('menu-scrolled');
  } else {
    mn.removeClass('menu-scrolled');
  }
};

left_menu_update = function($) {
  $('#cssmenu li.active').addClass('open').children('ul').show();
  $('#cssmenu li.has-sub>a').on('click', function() {
    var element;
    $(this).removeAttr('href');
    element = $(this).parent('li');
    if (element.hasClass('open')) {
      element.removeClass('open');
      element.find('li').removeClass('open');
      element.find('ul').slideUp(200);
    } else {
      element.addClass('open');
      element.children('ul').slideDown(200);
      element.siblings('li').children('ul').slideUp(200);
      element.siblings('li').removeClass('open');
      element.siblings('li').find('li').removeClass('open');
      element.siblings('li').find('ul').slideUp(200);
    }
  });
};

social_hover = function() {
  return $("#git-social").on({
    mouseenter: function() {
      $("#git-social").css("color", "#ff00ae");
      return $("#git-social >li >i").toggleClass('zmdi-github zmdi-github-alt');
    },
    mouseleave: function() {
      $("#git-social").css("color", "inherit");
      return $("#git-social >li >i").toggleClass('zmdi-github zmdi-github-alt');
    }
  });
};

$(document).ready(function() {
  return load_parts();
});

load_parts = function() {
  $("#header").load("header.html");
  return $("#footer").load("footer.html", all_scripts);
};

all_scripts = function() {
  ion.sound({
    sounds: [
      {
        name: "camera_flashing"
      }
    ],
    volume: 0.5,
    path: "sounds/",
    preload: true,
    multiplay: true
  });
  slider_toggle();
  social_hover();
  main_menu_update();
  $('#profile').click(function(e) {
    head_panel_click_open();
    return e.stopPropagation();
  });
  left_menu_update(jQuery);
  $(window).scroll(main_menu_update);
  $(document).click(function(e) {
    return head_panel_close();
  });
  return $("input[name='rating']").change(rating);
};

rating = function() {
  var vl;
  vl = parseInt($('input[name="rating"]:checked').val(), 10);
  if (rat !== 0) {
    rat += vl;
    rat = rat / 2;
  } else {
    rat = vl;
  }
  $('input[name="rating"]').attr('checked', false);
  return $("#ratS").text(+rat.toFixed(2));
};

btn_click = function(e) {
  if ($(e).val().toString() === "") {
    return document.location.href = "../index.html";
  } else {
    return document.location.href = $(e).val();
  }
};

slider_toggle = function() {
  return $('#img').click(function() {
    ion.sound.play("camera_flashing");
    if ($('.header-slider').css('display') === 'none') {
      $(".header-slider").slideDown();
      return $('#img').removeClass('img-gray');
    } else {
      $('#img').addClass('img-gray');
      return $(".header-slider").slideUp();
    }
  });
};
